import type { Food } from "./nutrition-diary-storage";

export const usdaCommonFoods: Food[] = [
  {
    id: "usda-apple-raw",
    name: "Apple",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 52,
    protein: 0,
    carbs: 14,
    fat: 0
  },
  {
    id: "usda-avocado-raw",
    name: "Avocado",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15
  },
  {
    id: "usda-blueberries-raw",
    name: "Blueberries",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 57,
    protein: 1,
    carbs: 14,
    fat: 0
  },
  {
    id: "usda-strawberries-raw",
    name: "Strawberries",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 32,
    protein: 1,
    carbs: 8,
    fat: 0
  },
  {
    id: "usda-orange-raw",
    name: "Orange",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 47,
    protein: 1,
    carbs: 12,
    fat: 0
  },
  {
    id: "usda-grapes-raw",
    name: "Grapes",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 69,
    protein: 1,
    carbs: 18,
    fat: 0
  },
  {
    id: "usda-chicken-breast-cooked",
    name: "Chicken breast, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 4
  },
  {
    id: "usda-chicken-thigh-cooked",
    name: "Chicken thigh, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 209,
    protein: 26,
    carbs: 0,
    fat: 11
  },
  {
    id: "usda-turkey-breast-cooked",
    name: "Turkey breast, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 135,
    protein: 30,
    carbs: 0,
    fat: 1
  },
  {
    id: "usda-ground-beef-90-cooked",
    name: "Ground beef, 90% lean, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 217,
    protein: 26,
    carbs: 0,
    fat: 12
  },
  {
    id: "usda-pork-chop-cooked",
    name: "Pork chop, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 231,
    protein: 26,
    carbs: 0,
    fat: 14
  },
  {
    id: "usda-salmon-cooked",
    name: "Salmon, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 12
  },
  {
    id: "usda-tuna-canned-water",
    name: "Tuna, canned in water",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1
  },
  {
    id: "usda-shrimp-cooked",
    name: "Shrimp, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 99,
    protein: 24,
    carbs: 0,
    fat: 0
  },
  {
    id: "usda-egg-whole",
    name: "Egg, whole",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 143,
    protein: 13,
    carbs: 1,
    fat: 10
  },
  {
    id: "usda-egg-white",
    name: "Egg whites",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 52,
    protein: 11,
    carbs: 1,
    fat: 0
  },
  {
    id: "usda-whole-milk",
    name: "Milk, whole",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 61,
    protein: 3,
    carbs: 5,
    fat: 3
  },
  {
    id: "usda-greek-yogurt-nonfat",
    name: "Greek yogurt, plain nonfat",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 59,
    protein: 10,
    carbs: 4,
    fat: 0
  },
  {
    id: "usda-cottage-cheese-lowfat",
    name: "Cottage cheese, lowfat",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 82,
    protein: 11,
    carbs: 3,
    fat: 2
  },
  {
    id: "usda-cheddar-cheese",
    name: "Cheddar cheese",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 403,
    protein: 25,
    carbs: 1,
    fat: 33
  },
  {
    id: "usda-firm-tofu",
    name: "Tofu, firm",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 144,
    protein: 17,
    carbs: 3,
    fat: 9
  },
  {
    id: "usda-lentils-cooked",
    name: "Lentils, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0
  },
  {
    id: "usda-black-beans-cooked",
    name: "Black beans, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 132,
    protein: 9,
    carbs: 24,
    fat: 1
  },
  {
    id: "usda-chickpeas-cooked",
    name: "Chickpeas, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 164,
    protein: 9,
    carbs: 27,
    fat: 3
  },
  {
    id: "usda-white-rice-cooked",
    name: "White rice, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 130,
    protein: 3,
    carbs: 28,
    fat: 0
  },
  {
    id: "usda-brown-rice-cooked",
    name: "Brown rice, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 123,
    protein: 3,
    carbs: 26,
    fat: 1
  },
  {
    id: "usda-pasta-cooked",
    name: "Pasta, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 158,
    protein: 6,
    carbs: 31,
    fat: 1
  },
  {
    id: "usda-quinoa-cooked",
    name: "Quinoa, cooked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 120,
    protein: 4,
    carbs: 21,
    fat: 2
  },
  {
    id: "usda-sweet-potato-baked",
    name: "Sweet potato, baked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 90,
    protein: 2,
    carbs: 21,
    fat: 0
  },
  {
    id: "usda-potato-baked",
    name: "Potato, baked",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 93,
    protein: 3,
    carbs: 21,
    fat: 0
  },
  {
    id: "usda-oats-dry",
    name: "Oats, dry",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7
  },
  {
    id: "usda-whole-wheat-bread",
    name: "Whole wheat bread",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 4
  },
  {
    id: "usda-peanut-butter",
    name: "Peanut butter",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50
  },
  {
    id: "usda-almonds",
    name: "Almonds",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50
  },
  {
    id: "usda-olive-oil",
    name: "Olive oil",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100
  },
  {
    id: "usda-butter",
    name: "Butter",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 717,
    protein: 1,
    carbs: 0,
    fat: 81
  },
  {
    id: "usda-honey",
    name: "Honey",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 304,
    protein: 0,
    carbs: 82,
    fat: 0
  },
  {
    id: "usda-raisins",
    name: "Raisins",
    brand: "USDA common foods",
    serving: "100 g",
    baseGrams: 100,
    calories: 299,
    protein: 3,
    carbs: 79,
    fat: 0
  }
];
